### ISSUE TITLE
I see all the WP form plugins but what about manual html forms?

### ISSUE THREAD

**Issue by quadcom** [mosparo/mautic-plugin#1]
I'm currently using Mautic as my forms processor and have integrated Google ReCaptchav3 as it's supported in Mautic, and I needed something because the spam was nuts.

But ReCaptcha is....a bit of a pain, forcing a font download even if you're already using Roboto on the site everywhere else. It would be great if I could get something in-house like Mosparo to replace it.

The forms from Mautic are straight-up, plain jane HTML forms with a little JScript thrown in. There's no need for a forms plugin to do a simple 4 field form -if you know how to do simple code, that is, which I do.

Should I go the custom integration route instead of this plugin?

 I'm all for open-source projects!

**Comment by zepich** [comment]
Hi quadcom

Thank you very much for the submitted issue.

mosparo has two parts:
- the frontend validation
- the backend verification

These two parts are needed to ensure the submission is correctly checked and processed. The form must be checked for spam content in the frontend validation. In the backend verification, we must ensure that the data was not changed after the validation.

In general, you can easily integrate the frontend part of mosparo by adding the needed HTML and JavaScript code. But that does not include the backend verification. The backend verification must be built into the system, which processes the data (for example, sending the email). For this, you have to add the verification code before the submitted form data will be processed. A plugin or addon usually does this for the systems (like WordPress or, in your example Mautic).

When I read your message, it was the first I had heard of Mautic. I've just looked at the documentation of Mautic, and in general, it should be no problem for us to write a plugin. I will look closer in the coming days and inform you about that topic.

How you can integrate mosparo you can find in our documentation here (you probably already saw that):

Frontend: https://documentation.mosparo.io/docs/integration/custom#add-container
Backend: https://documentation.mosparo.io/docs/integration/custom#performing-verification

I will inform you as soon as I have more information regarding Mautic.

**Comment by zepich** [comment]
Hi @quadcom

It took us some time, but I can finally announce that our Mautic plugin is developed and ready to use. You can download the plugin as a Zip file from the [release page](https://github.com/mosparo/mautic-plugin/releases/tag/v1.0-beta.1). The installation with Composer is not working right now because the bundle needs to be indexed in Packagist for Composer v1. I hope the bundle will soon be available in the Packagist index for Composer v1. You can find the complete installation instructions in the [README.md](https://github.com/mosparo/mautic-plugin/blob/master/README.md) file.

We've tagged the release as `beta-1` since we're not Mautic experts and would like to get feedback from you (and other Mautic users) before we can recommend using the plugin in a production environment.

Please do not hesitate to create an issue if you have any questions or problems. I will close this issue since there is now a plugin for Mautic. :)

Thank you very much for your idea, help, and feedback!

Kind regards,

zepich
